uploads = []
generated = []

[[outputs]]
id = "p-TaWSlpj23UXFctBHCjW"
uri = "file://03_seed_crm_workers.txt"
type = "text"
title = "03_seed_crm_workers.sql"

[[outputs]]
id = "glTGPdlR-gscNOdMaDnah"
uri = "file://bullenhaus_full_migration.txt"
type = "text"
title = "bullenhaus_full_migration.sql"

[[outputs]]
id = "BEfXLRRQjyNaKUN02Uch3"
uri = "file://confirm_all_users.txt"
type = "text"
title = "confirm_all_users.sql"
